print("GitHub 檔案讀取成功！")
local OrionLib = loadstring(game:HttpGet('https://raw.githubusercontent.com/shlexware/Orion/main/source'))()
local Window = OrionLib:MakeWindow({Name = "MasterHub V3", HidePremium = true})
local Tab = Window:MakeTab({Name = "功能"})
Tab:AddButton({Name = "成功了！", Callback = function() print("Works!") end})
OrionLib:Init()
